name: arabic_pharmacy
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.2
  package_info: ^2.0.2
  super_clipboard: ^0.8.2+1
  geolocator: ^10.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/pharmacy.png
    - assets/data/pharmacies.json
  fonts:
    - family: Almarai
      fonts:
        - asset: assets/Fonts/Almarai-Regular.ttf
